### ISSUE TITLE
Função incoerente 

### ISSUE THREAD

**Issue by rafaelgalle** [andrelsmelo/exerc-php#2]
Função não realiza oq o nome se propõe a fazer, não esta fazendo sentido. 

https://github.com/andrelsmelo/exerc-php/blob/e4e8beffd9026ff2d8cbd0d25586625993b38d40/controllers/persons.php#L30

**Comment by andrelsmelo** [comment]
Removido Arquivo persons.php onde se encontrava a mesma função.
