### ISSUE TITLE
Cuidar com dependências 

### ISSUE THREAD

**Issue by rafaelgalle** [andrelsmelo/exerc-php#3]
Cuidar ao importar dependências, você esta importando duas versões do jquery diferentes, só é necessário uma versão do jquery.

https://github.com/andrelsmelo/exerc-php/blob/e4e8beffd9026ff2d8cbd0d25586625993b38d40/views/getData.php#L63
https://github.com/andrelsmelo/exerc-php/blob/e4e8beffd9026ff2d8cbd0d25586625993b38d40/views/getData.php#L66

**Comment by andrelsmelo** [comment]
Ajustado.
