### ISSUE TITLE
Code smells

### ISSUE THREAD

**Issue by rafaelgalle** [andrelsmelo/exerc-php#4]
Essa função esta muito grande, com muitos ifs dentro dela, e fazendo mais doq o nome se propõe a fazer.
Talvez o calculo de média possa fazer parte de outra função, e a lógica utilizada pra fazer a média também pode ser melhorada.

https://github.com/andrelsmelo/exerc-php/blob/e4e8beffd9026ff2d8cbd0d25586625993b38d40/controllers/functions.php#L27-L70

**Comment by andrelsmelo** [comment]
Ajustado logica para calculo de media utilizando foreach, dividido funçõs para calculo de média dependendo de quantos anos foram declarados e função para visualização de mensagem final.
